apiVersion: v1
kind: Pod
metadata:
  name: postgre-workload-35
  labels:
    app: postgre-workload
    workload-type: postgre
    run-id: "mdrs_random_1"
    scheduler: "dqn-scheduler"
spec:
  schedulerName: dqn-scheduler
  restartPolicy: Never
  containers:
  - name: postgre-app
    image: fathiimran/workload-postgre:1.2
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "429m"
        memory: "512Mi"
      limits:
        cpu: "429m"
        memory: "512Mi"
    envFrom:
    - configMapRef:
        name: db-workload-config
