apiVersion: v1
kind: Pod
metadata:
  name: postgre-workload-10
  labels:
    app: postgre-workload
    workload-type: postgre
    run-id: "20260516_074107"
    scheduler: "default-scheduler"
spec:
  schedulerName: default-scheduler
  restartPolicy: Never
  containers:
  - name: postgre-app
    image: fathiimran/workload-postgre:1.2
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "474m"
        memory: "512Mi"
      limits:
        cpu: "474m"
        memory: "512Mi"
    envFrom:
    - configMapRef:
        name: db-workload-config
