apiVersion: v1
kind: Pod
metadata:
  name: fusion-workload-38
  labels:
    app: fusion-workload
    workload-type: fusion
    run-id: "drs_fusion-only_1"
    scheduler: "dqn-scheduler"
spec:
  schedulerName: dqn-scheduler
  restartPolicy: Never
  containers:
  - name: fusion-app
    image: fathiimran/workload-fusion:1.2
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "417m"
        memory: "512Mi"
      limits:
        cpu: "417m"
        memory: "512Mi"
    envFrom:
    - configMapRef:
        name: db-workload-config
