apiVersion: v1
kind: Pod
metadata:
  name: mongo-workload-8
  labels:
    app: mongo-workload
    workload-type: mongo
    run-id: "20260512_024505"
    scheduler: "default-scheduler"
spec:
  schedulerName: default-scheduler
  restartPolicy: Never
  containers:
  - name: mongo-app
    image: fathiimran/workload-mongo:1.2
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "421m"
        memory: "512Mi"
      limits:
        cpu: "421m"
        memory: "512Mi"
    envFrom:
    - configMapRef:
        name: db-workload-config
