apiVersion: v1
kind: Pod
metadata:
  name: fusion-workload-58
  labels:
    app: fusion-workload
    workload-type: fusion
    run-id: "20260516_084621"
    scheduler: "default-scheduler"
spec:
  schedulerName: default-scheduler
  restartPolicy: Never
  containers:
  - name: fusion-app
    image: fathiimran/workload-fusion:1.2
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "204m"
        memory: "512Mi"
      limits:
        cpu: "204m"
        memory: "512Mi"
    envFrom:
    - configMapRef:
        name: db-workload-config
