apiVersion: v1
kind: Pod
metadata:
  name: fusion-v2-workload-7
  labels:
    app: fusion-v2-workload
    workload-type: fusion-v2
    run-id: "20260516_110258"
    scheduler: "dqn-scheduler"
spec:
  schedulerName: dqn-scheduler
  restartPolicy: Never
  containers:
  - name: fusion-v2-app
    image: fathiimran/workload-fusion-v2:1.2
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "297m"
        memory: "512Mi"
      limits:
        cpu: "297m"
        memory: "512Mi"
    envFrom:
    - configMapRef:
        name: db-workload-config
